### ISSUE TITLE
Cannot Generate Genesis.ssz

### ISSUE THREAD

**Issue by avenbreaks** [protolambda/eth2-testnet-genesis#13]
hello, I have genesis.json and some files to be merged but when I want to merge those files I get an error.
actually i built my public blockchain with customization in genesis.json, config.yaml.

```
❯ eth2-testnet-genesis merge \
  --config "/home/Desktop/gitshock-client/config.yaml" \
  --eth1-config "/home/Desktop/gitshock-client/genesis.json" \
  --mnemonics "/home/Desktop/gitshock-client/mnemonics.yaml"
```

Logs : 
```
using eth1 config to create and embed ExecutionPayloadHeader in genesis BeaconState
extra data is 117 bytes, max is 32
```

**Comment by avenbreaks** [comment]
@protolambda

**Comment by protolambda** [comment]
read the error message. The extra data in your genesis.json execution layer block is too long

**Comment by avenbreaks** [comment]
> read the error message. The extra data in your genesis.json execution layer block is too long

thankyou sir, solved! 

but I want to ask something about bootnodes, I want to create my own bootnodes how do I get it? because what I read in the GETH documentation should be like this `geth init --datadir ./keystore genesis.json` and enter new console mode I see bootnode and enr. and these are good tools but I'm confused about entering ENR or bootnodes

**Comment by q9f** [comment]
`geth init` only initializes the node. you have to run geth from the same datadir. then you can get the `enode` entry from geth to bootstrap other nodes.

**Comment by youngerq** [comment]
> > read the error message. The extra data in your genesis.json execution layer block is too long
> 
> thankyou sir, solved!
> 
> but I want to ask something about bootnodes, I want to create my own bootnodes how do I get it? because what I read in the GETH documentation should be like this `geth init --datadir ./keystore genesis.json` and enter new console mode I see bootnode and enr. and these are good tools but I'm confused about entering ENR or bootnodes

I also encountered this problem. How to solve the problem of too long extradata The execution layer extradata of the poa is more than 32. The genis.ssz generated by specifying the block number and the block hash cannot be read by Prysm
