### ISSUE TITLE
how do i install this on a linux server ?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [protolambda/eth2-testnet-genesis#32]
I am not expert in Go Programming Language

How do i install this program to work globally on a ubuntu server

**Comment by chong-he** [comment]
To install `go`, follow the instructions here: https://go.dev/doc/install

Once you install `go`, you can then run `make` in the repository, which will compile a binary file `eth2-testnet-genesis`. If you want this binary file to work globally, you can copy it to any directory in the `$PATH`, for example, `/usr/local/bin`
